import { 
  Gamepad2, 
  Phone, 
  MessageCircle, 
  User, 
  Settings, 
  Camera, 
  Image as ImageIcon, 
  Clock, 
  Calculator, 
  Calendar, 
  FileText, 
  MapPin, 
  CloudSun, 
  Globe, 
  Mic, 
  FolderOpen, 
  HeartPulse, 
  Newspaper, 
  TrendingUp, 
  QrCode, 
  Languages, 
  Hash, 
  Flashlight, 
  RotateCcw,
  Compass, 
  Music, 
  PlayCircle, 
  Mail, 
  CheckCircle, 
  Book, 
  ListTodo, 
  ShoppingBag,
  Trophy,
  Zap,
  Target,
  Grid3X3,
  Brain,
  Sword,
  Ghost,
  Coins,
  Joystick,
  Circle
} from 'lucide-react';

export interface AppConfig {
  id: string;
  name: string;
  icon: any;
  category: 'game' | 'utility';
  color: string;
  isSystem?: boolean;
}

export const APPS: AppConfig[] = [
  // Games (20)
  // Football Games (10)
  { id: 'game-fb-1', name: 'DLS 26', icon: Trophy, category: 'game', color: 'bg-emerald-600' },
  { id: 'game-fb-2', name: 'FC Mobile', icon: Trophy, category: 'game', color: 'bg-blue-600' },
  { id: 'game-fb-3', name: 'FIFA 26', icon: Trophy, category: 'game', color: 'bg-green-700' },
  { id: 'game-fb-4', name: 'PES 26', icon: Trophy, category: 'game', color: 'bg-indigo-700' },
  { id: 'game-fb-5', name: 'Soccer Star', icon: Target, category: 'game', color: 'bg-emerald-500' },
  { id: 'game-fb-6', name: 'Top Eleven', icon: Target, category: 'game', color: 'bg-blue-500' },
  { id: 'game-fb-7', name: 'Football Mgr', icon: Trophy, category: 'game', color: 'bg-slate-700' },
  { id: 'game-fb-8', name: 'Score! Hero', icon: Target, category: 'game', color: 'bg-red-500' },
  { id: 'game-fb-9', name: 'Futbol Pro', icon: Trophy, category: 'game', color: 'bg-emerald-800' },
  { id: 'game-fb-10', name: 'Koptoq', icon: Target, category: 'game', color: 'bg-green-600' },

  { id: 'game-coins', name: 'Tanga Terish', icon: Coins, category: 'game', color: 'bg-yellow-600' },

  // Racing Games (9)
  { id: 'game-rc-1', name: 'Racing Pro', icon: Zap, category: 'game', color: 'bg-red-600' },
  { id: 'game-rc-2', name: 'AutoSpeed', icon: Zap, category: 'game', color: 'bg-orange-600' },
  { id: 'game-rc-3', name: 'Asphalt 10', icon: Zap, category: 'game', color: 'bg-blue-800' },
  { id: 'game-rc-4', name: 'Need for Spd', icon: Zap, category: 'game', color: 'bg-gray-900' },
  { id: 'game-rc-5', name: 'F1 Mobile', icon: Target, category: 'game', color: 'bg-red-700' },
  { id: 'game-rc-6', name: 'Moto GP', icon: Zap, category: 'game', color: 'bg-blue-500' },
  { id: 'game-rc-7', name: 'Drift Max', icon: RotateCcw, category: 'game', color: 'bg-slate-800' },
  { id: 'game-rc-8', name: 'Offroad 4x4', icon: Target, category: 'game', color: 'bg-amber-900' },
  { id: 'game-rc-9', name: 'Kart Racing', icon: Ghost, category: 'game', color: 'bg-pink-600' },
  { id: 'game-rc-10', name: 'Truck Sim', icon: Zap, category: 'game', color: 'bg-cyan-800' },

  // Utilities (70)
  { id: 'phone', name: 'Phone', icon: Phone, category: 'utility', color: 'bg-white', isSystem: true },
  { id: 'messages', name: 'Messages', icon: MessageCircle, category: 'utility', color: 'bg-white', isSystem: true },
  { id: 'contacts', name: 'Contacts', icon: User, category: 'utility', color: 'bg-white', isSystem: true },
  { id: 'settings', name: 'Settings', icon: Settings, category: 'utility', color: 'bg-white', isSystem: true },
  { id: 'camera', name: 'Camera', icon: Camera, category: 'utility', color: 'bg-[#333]' },
  { id: 'gallery', name: 'Gallery', icon: ImageIcon, category: 'utility', color: 'bg-[#bc8f8f]' },
  { id: 'clock', name: 'Clock', icon: Clock, category: 'utility', color: 'bg-[#4a523a]' },
  { id: 'calculator', name: 'Calculator', icon: Calculator, category: 'utility', color: 'bg-[#8a9a5b]' },
  { id: 'calendar', name: 'Calendar', icon: Calendar, category: 'utility', color: 'bg-[#4682b4]' },
  { id: 'notes', name: 'Notes', icon: FileText, category: 'utility', color: 'bg-[#bc8f8f]' },
  { id: 'maps', name: 'Maps', icon: MapPin, category: 'utility', color: 'bg-[#708090]' },
  { id: 'weather', name: 'Weather', icon: CloudSun, category: 'utility', color: 'bg-[#8fbc8f]' },
  { id: 'browser', name: 'Internet', icon: Globe, category: 'utility', color: 'bg-[#483d8b]' },
  { id: 'voice', name: 'Recorder', icon: Mic, category: 'utility', color: 'bg-[#cd5c5c]' },
  { id: 'files', name: 'My Files', icon: FolderOpen, category: 'utility', color: 'bg-[#778899]' },
  { id: 'health', name: 'Health', icon: HeartPulse, category: 'utility', color: 'bg-[#556b2f]' },
  { id: 'news', name: 'News', icon: Newspaper, category: 'utility', color: 'bg-[#2f4f4f]' },
  { id: 'stocks', name: 'Stocks', icon: TrendingUp, category: 'utility', color: 'bg-[#4682b4]' },
  { id: 'qr', name: 'QR', icon: QrCode, category: 'utility', color: 'bg-[#333]' },
  { id: 'translator', name: 'Translate', icon: Languages, category: 'utility', color: 'bg-[#5f9ea0]' },
  { id: 'unit', name: 'Unit Conv', icon: Hash, category: 'utility', color: 'bg-[#bdb76b]' },
  { id: 'torch', name: 'Flashlight', icon: Flashlight, category: 'utility', color: 'bg-[#daa520]' },
  { id: 'compass', name: 'Compass', icon: Compass, category: 'utility', color: 'bg-[#2f4f4f]' },
  { id: 'music', name: 'Music', icon: Music, category: 'utility', color: 'bg-[#cd853f]' },
  { id: 'video', name: 'Video', icon: PlayCircle, category: 'utility', color: 'bg-[#483d8b]' },
  { id: 'email', name: 'Email', icon: Mail, category: 'utility', color: 'bg-[#cd5c5c]' },
  { id: 'habits', name: 'Habits', icon: CheckCircle, category: 'utility', color: 'bg-[#556b2f]' },
  { id: 'dictionary', name: 'Dictionary', icon: Book, category: 'utility', color: 'bg-[#8b4513]' },
  { id: 'todo', name: 'To-Do', icon: ListTodo, category: 'utility', color: 'bg-[#4682b4]' },
  { id: 'store', name: 'Play Market', icon: ShoppingBag, category: 'utility', color: 'bg-[#bc8f8f]' },
  { id: 'youtube', name: 'YouTube', icon: PlayCircle, category: 'utility', color: 'bg-red-600' },
  { id: 'chatgpt', name: 'ChatGPT', icon: Brain, category: 'utility', color: 'bg-[#10a37f]' },
  { id: 'facebook', name: 'Facebook', icon: Globe, category: 'utility', color: 'bg-blue-600' },
  { id: 'instagram', name: 'Instagram', icon: Camera, category: 'utility', color: 'bg-pink-500' },
  { id: 'telegram', name: 'Telegram', icon: MessageCircle, category: 'utility', color: 'bg-sky-500' },
  { id: 'spotify', name: 'Spotify', icon: Music, category: 'utility', color: 'bg-green-500' },
  { id: 'tiktok', name: 'TikTok', icon: Zap, category: 'utility', color: 'bg-black' },
  { id: 'twitter', name: 'Twitter', icon: Hash, category: 'utility', color: 'bg-[#1DA1F2]' },
  { id: 'zoom', name: 'Zoom', icon: PlayCircle, category: 'utility', color: 'bg-blue-400' },
  { id: 'slack', name: 'Slack', icon: MessageCircle, category: 'utility', color: 'bg-purple-600' },
  { id: 'linkedin', name: 'LinkedIn', icon: User, category: 'utility', color: 'bg-blue-800' },
  { id: 'amazon', name: 'Amazon', icon: ShoppingBag, category: 'utility', color: 'bg-orange-500' },
  { id: 'netflix', name: 'Netflix', icon: PlayCircle, category: 'utility', color: 'bg-red-700' },
  { id: 'uber', name: 'Uber', icon: MapPin, category: 'utility', color: 'bg-black' },
  { id: 'dominos', name: 'Domino\'s', icon: ShoppingBag, category: 'utility', color: 'bg-blue-600' },
  { id: 'duolingo', name: 'Duolingo', icon: Languages, category: 'utility', color: 'bg-green-400' },
  { id: 'discord', name: 'Discord', icon: MessageCircle, category: 'utility', color: 'bg-indigo-500' },
  { id: 'twitch', name: 'Twitch', icon: PlayCircle, category: 'utility', color: 'bg-purple-500' },
  { id: 'reddit', name: 'Reddit', icon: Globe, category: 'utility', color: 'bg-orange-600' },
  { id: 'pinterest', name: 'Pinterest', icon: ImageIcon, category: 'utility', color: 'bg-red-600' },
  { id: 'canva', name: 'Canva', icon: ImageIcon, category: 'utility', color: 'bg-blue-500' },
  { id: 'notion', name: 'Notion', icon: FileText, category: 'utility', color: 'bg-black' },
  { id: 'trello', name: 'Trello', icon: ListTodo, category: 'utility', color: 'bg-blue-600' },
  { id: 'asana', name: 'Asana', icon: CheckCircle, category: 'utility', color: 'bg-rose-500' },
  { id: 'stripe', name: 'Stripe', icon: Coins, category: 'utility', color: 'bg-indigo-600' },
  { id: 'paypal', name: 'PayPal', icon: Coins, category: 'utility', color: 'bg-blue-900' },
  { id: 'wallet', name: 'Wallet', icon: Coins, category: 'utility', color: 'bg-gray-800' },
  { id: 'passwords', name: 'Passwd', icon: Target, category: 'utility', color: 'bg-blue-600' },
  { id: 'health-plus', name: 'Health+', icon: HeartPulse, category: 'utility', color: 'bg-emerald-500' },
  { id: 'meditation', name: 'Calm', icon: CloudSun, category: 'utility', color: 'bg-indigo-400' },
  { id: 'fitness', name: 'Fit', icon: Zap, category: 'utility', color: 'bg-orange-600' },
  { id: 'recipes', name: 'Chef', icon: FileText, category: 'utility', color: 'bg-amber-600' },
  { id: 'booking', name: 'Travel', icon: MapPin, category: 'utility', color: 'bg-blue-700' },
  { id: 'shazam', name: 'Shazam', icon: Music, category: 'utility', color: 'bg-blue-500' },
  { id: 'translator-pro', name: 'Trans', icon: Languages, category: 'utility', color: 'bg-sky-600' },
  { id: 'keyboard', name: 'Kbd', icon: Settings, category: 'utility', color: 'bg-gray-600' },
  { id: 'flashlight-pro', name: 'Beam', icon: Flashlight, category: 'utility', color: 'bg-yellow-400' },
  { id: 'world-clock', name: 'Clock+', icon: Clock, category: 'utility', color: 'bg-black' },
  { id: 'extra-1', name: 'App 89', icon: Grid3X3, category: 'utility', color: 'bg-gray-400' },
  { id: 'extra-2', name: 'App 90', icon: Grid3X3, category: 'utility', color: 'bg-gray-400' },
];
